# Generated by Django 3.0.5 on 2021-03-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Tables')),
            ],
        ),
        migrations.CreateModel(
            name='Feet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('legs', models.ManyToManyField(to='webapp.Legs')),
            ],
        ),
    ]
